import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';
import { PropsWithChildren } from 'react';
import ErrorBoundary from 'shared/ui/ErrorBoundary/ErrorBoundary';
import { HeaderWidget } from 'widgets/Header';
import ReduxProvider from './_providers/ReduxProvider';
import './index.css';

import cn from 'classnames';
import { Footer } from 'widgets/Footer';
const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' });

const rubik = Rubik({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-rubik',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: '/favicon.ico',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
    return (
        <html lang='en'>
            <body className={cn(inter.className, rubik.className)}>
                <ReduxProvider>
                    <ErrorBoundary>
                        <HeaderWidget />

                        <div className='max-w-[1200px] flex flex-col items-center justify-center m-auto'>
                            {children}
                        </div>
                        <Footer />
                    </ErrorBoundary>
                </ReduxProvider>
            </body>
        </html>
    );
};
export default RootLayout;
