import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import ErrorBoundary from 'shared/ui/ErrorBoundary/ErrorBoundary';
import ReduxProvider from './_providers/ReduxProvider';
import './index.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: '/favicon.ico',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ReduxProvider>
                    <ErrorBoundary> {children}</ErrorBoundary>
                </ReduxProvider>
            </body>
        </html>
    );
};
export default RootLayout;
